# Generated by Django 4.2 on 2026-07-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
